name: "Setup Docker Compose"
description: "Setup Docker Compose For Github Actions CI/CD"
inputs:
  DEBUG:
    required: true
  LOG_LEVEL:
    required: true
  BOT_TOKEN:
    required: true
  DATABASE_USER:
    required: true
  DATABASE_PASSWORD:
    required: true
  DATABASE_HOST:
    required: true
  DATABASE_PORT:
    required: true
  DATABASE_NAME:
    required: true
  REDIS_HOST:
    required: true
  REDIS_PORT:
    required: true
  REDIS_PASSWORD:
    required: true
  REDIS_DB:
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Setup Docker Compose 
      uses: docker/setup-compose-action@v1
      with:
        version: "latest"

    - name: Create .env file for docker-compose
      run: |
        cat <<EOF > .env
        DEBUG=${{ inputs.DEBUG }}
        LOG_LEVEL=${{ inputs.LOG_LEVEL }}
        BOT_TOKEN=${{ inputs.BOT_TOKEN }}
        DATABASE_USER=${{ inputs.DATABASE_USER }}
        DATABASE_PASSWORD=${{ inputs.DATABASE_PASSWORD }}
        DATABASE_HOST=${{ inputs.DATABASE_HOST }}
        DATABASE_PORT=${{ inputs.DATABASE_PORT }}
        DATABASE_NAME=${{ inputs.DATABASE_NAME }}
        REDIS_HOST=${{ inputs.REDIS_HOST }}
        REDIS_PORT=${{ inputs.REDIS_PORT }}
        REDIS_PASSWORD=${{ inputs.REDIS_PASSWORD }}
        REDIS_DB=${{ inputs.REDIS_DB }}
        EOF
      shell: bash

    - name: Build Docker Images
      run: make ci-build
      shell: bash

    - name: Up Docker Containers
      run: make ci-up
      shell: bash

    - name: Run Migrations
      run: make ci-migrate
      shell: bash
