"""empty message

Revision ID: 1295bee80ee4
Revises: 317b9f02ca16
Create Date: 2025-08-11 17:43:10.219214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1295bee80ee4'
down_revision: Union[str, Sequence[str], None] = '317b9f02ca16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('UZ', 'RU', 'EN', name='userlanguages').create(op.get_bind())
    op.create_table('user_auth',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    op.drop_table('user_tg_auth')
    op.alter_column('user_languages', 'language',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('UZ', 'RU', 'EN', name='userlanguages'),
               existing_nullable=False,
               postgresql_using='language::userlanguages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_languages', 'language',
               existing_type=sa.Enum('UZ', 'RU', 'EN', name='userlanguages'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('user_tg_auth',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_tg_auth_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'chat_id', name=op.f('user_tg_auth_pkey'))
    )
    op.drop_table('user_auth')
    sa.Enum('UZ', 'RU', 'EN', name='userlanguages').drop(op.get_bind())
    # ### end Alembic commands ###
