"""messages.text_id can be None

Revision ID: 12ff488d3ae8
Revises: a6401a37b566
Create Date: 2025-09-11 15:42:13.996693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ff488d3ae8'
down_revision: Union[str, Sequence[str], None] = 'a6401a37b566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'text_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'text_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
