"""messages.text_id can be None

Revision ID: 12ff488d3ae8
Revises: a6401a37b566
Create Date: 2025-09-11 15:42:13.996693

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '12ff488d3ae8'
down_revision: str | Sequence[str] | None = 'a6401a37b566'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
