"""Database Fully Recreate

Revision ID: 2841c9180dc3
Revises: 308162c744c9
Create Date: 2025-09-06 12:53:15.019290

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2841c9180dc3'
down_revision: str | Sequence[str] | None = '308162c744c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('interval', sa.Interval(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tg_accounts',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('user_id', 'phone', name='user_id_phone_unique_constraint')
    )
    op.create_table('tg_groups',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username', 'owner_id', name='tg_groups_username_owner_id_unique_constraint')
    )
    op.create_table('tg_users',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='userlanguages', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('interval', sa.Interval(), nullable=False),
    sa.Column('repeat_count', sa.Integer(), nullable=False),
    sa.Column('max_repeat_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tg_accounts.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_languages')
    op.add_column('user_auth', sa.Column('username', sa.String(length=255), nullable=False))
    op.add_column('user_auth', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('user_auth', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False))
    op.add_column('user_auth', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False))
    op.drop_index(op.f('user_auth_chat_id_inx'), table_name='user_auth')
    op.create_index(op.f('ix_user_auth_username'), 'user_auth', ['username'], unique=True)
    op.drop_constraint(op.f('user_auth_user_id_fkey'), 'user_auth', type_='foreignkey')
    op.create_foreign_key(None, 'user_auth', 'users', ['user_id'], ['id'])
    op.drop_column('user_auth', 'chat_id')
    op.drop_column('users', 'username')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_auth', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_auth', type_='foreignkey')
    op.create_foreign_key(op.f('user_auth_user_id_fkey'), 'user_auth', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_auth_username'), table_name='user_auth')
    op.create_index(op.f('user_auth_chat_id_inx'), 'user_auth', ['chat_id'], unique=False)
    op.drop_column('user_auth', 'updated_at')
    op.drop_column('user_auth', 'created_at')
    op.drop_column('user_auth', 'password')
    op.drop_column('user_auth', 'username')
    op.create_table('user_languages',
    sa.Column('chat_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('language', postgresql.ENUM('UZ', 'RU', 'EN', name='userlanguages', create_type=False), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('user_languages_pkey'))
    )
    op.drop_table('schedules')
    op.drop_table('tg_users')
    op.drop_table('tg_groups')
    op.drop_table('tg_accounts')
    op.drop_table('messages')
    op.drop_table('texts')
    # ### end Alembic commands ###
