"""tg_groups change

Revision ID: 5e52b14b1d06
Revises: 2841c9180dc3
Create Date: 2025-09-06 15:18:36.075082

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5e52b14b1d06'
down_revision: str | Sequence[str] | None = '2841c9180dc3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tg_groups_username_owner_id_unique_constraint'), 'tg_groups', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('tg_groups_username_owner_id_unique_constraint'), 'tg_groups', ['username', 'owner_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
