"""messages.status added

Revision ID: 9bcdc8e2ab5d
Revises: adfa9e6f3628
Create Date: 2025-09-11 13:55:55.458581

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9bcdc8e2ab5d'
down_revision: str | Sequence[str] | None = 'adfa9e6f3628'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
