"""feedbacks table added

Revision ID: 9d9b36d734b0
Revises: 5e52b14b1d06
Create Date: 2025-09-10 13:45:52.636223

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9d9b36d734b0'
down_revision: str | Sequence[str] | None = '5e52b14b1d06'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NEW', 'IN_REVIEW', 'ANSWERED', 'CLOSED', name='feedbackstatus').create(op.get_bind())
    op.create_table('feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reply_message_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('NEW', 'IN_REVIEW', 'ANSWERED', 'CLOSED', name='feedbackstatus', create_type=False), nullable=False),
    sa.Column('message', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('UTC', NOW())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_chat_id'), 'feedbacks', ['chat_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_chat_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    sa.Enum('NEW', 'IN_REVIEW', 'ANSWERED', 'CLOSED', name='feedbackstatus').drop(op.get_bind())
    # ### end Alembic commands ###
