"""default is set

Revision ID: ab3b526c5e86
Revises: 9bcdc8e2ab5d
Create Date: 2025-09-11 13:57:24.250123

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ab3b526c5e86'
down_revision: str | Sequence[str] | None = '9bcdc8e2ab5d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('CREATED', 'STARTED', 'FINISHED', name='messagestatus').create(op.get_bind())
    op.add_column('messages', sa.Column('status', postgresql.ENUM('CREATED', 'STARTED', 'FINISHED', name='messagestatus', create_type=False), sa.Computed("\nCASE\n    WHEN started_at IS NULL THEN 'CREATED'\n    WHEN (started_at + duration) > NOW() THEN 'STARTED'\n    ELSE 'FINISHED'\nEND\n", persisted=True), nullable=False))
    op.alter_column('messages', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('messages', 'status')
    sa.Enum('CREATED', 'STARTED', 'FINISHED', name='messagestatus').drop(op.get_bind())
    # ### end Alembic commands ###
