"""fix: pk fix

Revision ID: bdcf582882d3
Revises: 303ca5ad77b7
Create Date: 2025-08-14 16:03:48.396511

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bdcf582882d3'
down_revision: str | Sequence[str] | None = '303ca5ad77b7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_auth_chat_id_inx', 'user_auth', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_auth_chat_id_inx', table_name='user_auth')
    # ### end Alembic commands ###
