#!/bin/sh
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy project files related to dependencies first for layer caching
COPY pyproject.toml uv.lock ./

# Install uv globally
RUN ["pip", "install", "--no-cache-dir", "uv"]

# Sync Dependencies
RUN ["uv", "sync", "--all-groups"]

# Copy the rest of the application code
COPY . .
