name: "Setup Docker Compose"
description: "Setup Docker Compose For Github Actions CI/CD"
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Docker Compose 
      uses: docker/setup-compose-action@v1
      with:
        version: "latest"

    - name: Create .env file for docker-compose
      run: |
        cat <<EOF > .env
        DEBUG=${{ secrets.DEBUG }}
        LOG_LEVEL=${{ secrets.LOG_LEVEL }}
        BOT_TOKEN=${{ secrets.BOT_TOKEN }}
        DATABASE_USER=${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
        DATABASE_HOST=${{ secrets.DATABASE_HOST }}
        DATABASE_PORT=${{ secrets.DATABASE_PORT }}
        DATABASE_NAME=${{ secrets.DATABASE_NAME }}
        REDIS_HOST=${{ secrets.REDIS_HOST }}
        REDIS_PORT=${{ secrets.REDIS_PORT }}
        REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
        REDIS_DB=${{ secrets.REDIS_DB }}
        EOF

    - name: Build Docker Images
      run: make ci-build

    - name: Up Docker Containers
      run: make ci-up

    - name: Run Migrations
      run: make ci-migrate
